name: Android - Build Release APK
on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      APP_DIR: S2PASS-Android/S2PASS-Android
      KEYSTORE_PATH: ${{ env.APP_DIR }}/release.keystore
      ANDROID_PLATFORM_PKG: platforms;android-34
      ANDROID_BUILD_TOOLS_PKG: build-tools;34.0.0

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Validate keystore secrets
      - name: Validate keystore secrets
        id: validate-secrets
        run: |
          missing=0
          [ -z "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ] && echo "❌ ANDROID_KEYSTORE_BASE64 missing" && missing=1
          [ -z "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" ] && echo "❌ ANDROID_KEYSTORE_PASSWORD missing" && missing=1
          [ -z "${{ secrets.ANDROID_KEY_ALIAS }}" ] && echo "❌ ANDROID_KEY_ALIAS missing" && missing=1
          [ -z "${{ secrets.ANDROID_KEY_PASSWORD }}" ] && echo "❌ ANDROID_KEY_PASSWORD missing" && missing=1
          exit $missing

      # Set up JDK 17 for the Android Gradle plugin (AGP 8.x requires Java 17)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          components: platform-tools, platforms;android-34, build-tools;34.0.0, tools
          ndk: ""

      # Accept Android SDK licenses
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      # Decode keystore from base64 secret
      - name: Decode keystore
        if: steps.validate-secrets.outputs.missing == '0'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > "$KEYSTORE_PATH"

      # Write keystore properties for signing
      - name: Write keystore properties
        if: steps.validate-secrets.outputs.missing == '0'
        run: |
          cat <<EOF > $APP_DIR/keystore.properties
          storeFile=$KEYSTORE_PATH
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF

      # Set up Gradle 8.1 (compatible with AGP 8.1.0)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1

      # Build the release APK
      - name: Build release APK
        working-directory: ${{ env.APP_DIR }}
        run: ./gradlew assembleRelease --no-daemon

      # Upload generated APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.APP_DIR }}/app/build/outputs/apk/release/app-release.apk
