name: Android – Build Release APK
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - uses: android-actions/setup-android@v3
      - name: Decode keystore from secrets
        env: { ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }} }
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > S2PASS-Android/S2PASS-Android/release.keystore
      - name: Write keystore.properties (CI-only)
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cat > S2PASS-Android/S2PASS-Android/app/keystore.properties <<'EOF'
          storeFile=../release.keystore
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF
      - name: Build Release APK
        working-directory: S2PASS-Android/S2PASS-Android
        run: ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: S2PASS-Android/S2PASS-Android/app/build/outputs/apk/release/*.apk
