# .github/workflows/android-release.yml
name: Android Build Final

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: S2PASS-Android/S2PASS-Android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Restore keystore
        run: |
          echo "$KEYSTORE_B64" | base64 -d > release.keystore
          cat > keystore.properties <<EOF
          storeFile=release.keystore
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

      - name: Build Release
        run: ./gradlew :app:assembleRelease --stacktrace

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: S2PASS-Android/S2PASS-Android/app/build/outputs/apk/release/*.apk
