name: Android CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Configure SDK path
        working-directory: S2PASS-Android/S2PASS-Android
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - name: Grant execute permission for gradlew
        working-directory: S2PASS-Android/S2PASS-Android
        run: chmod +x gradlew
      - name: Build debug APK
        working-directory: S2PASS-Android/S2PASS-Android
        run: ./gradlew assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: S2PASS-Android/S2PASS-Android/app/build/outputs/apk/debug/app-debug.apk
