name: Android - Build Release APK

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # NOTE: Only reference these in steps as $APP_DIR, $KEYSTORE_PATH, etc.
    env:
      APP_DIR: S2PASS-Android/S2PASS-Android
      KEYSTORE_PATH: S2PASS-Android/S2PASS-Android/release.keystore
      ANDROID_PLATFORM_PKG: platforms;android-34
      ANDROID_BUILD_TOOLS_PKG: build-tools;34.0.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure the 4 required secrets exist; fail fast if any are missing.
      - name: Validate keystore secrets
        id: validate-secrets
        shell: bash
        run: |
          missing=0
          if [ -z "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "::error title=Missing secret::ANDROID_KEYSTORE_BASE64"
            missing=1
          fi
          if [ -z "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" ]; then
            echo "::error title=Missing secret::ANDROID_KEYSTORE_PASSWORD"
            missing=1
          fi
          if [ -z "${{ secrets.ANDROID_KEY_ALIAS }}" ]; then
            echo "::error title=Missing secret::ANDROID_KEY_ALIAS"
            missing=1
          fi
          if [ -z "${{ secrets.ANDROID_KEY_PASSWORD }}" ]; then
            echo "::error title=Missing secret::ANDROID_KEY_PASSWORD"
            missing=1
          fi
          echo "missing=$missing" >> "$GITHUB_OUTPUT"
          if [ "$missing" -ne 0 ]; then
            exit 1
          fi

      # Java 17 required for modern AGP
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Install Android SDK + tools and accept licenses
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept SDK licenses
        shell: bash
        run: yes | sdkmanager --licenses

      # Decode keystore file from base64 secret
      - name: Decode keystore
        if: steps.validate-secrets.outputs.missing == '0'
        shell: bash
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > "$KEYSTORE_PATH"

      # ✅ FIXED: Properly write keystore.properties via here-doc
      - name: Write keystore properties
        if: steps.validate-secrets.outputs.missing == '0'
        shell: bash
        run: |
          cat <<EOF > "$APP_DIR/keystore.properties"
          storeFile=$KEYSTORE_PATH
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF

      # Optional but recommended: Gradle wrapper validation + caching
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1

      - name: Build release APK
        working-directory: ${{ env.APP_DIR }}
        shell: bash
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.APP_DIR }}/app/build/outputs/apk/release/app-release.apk
